# Generated by Django 5.2.1 on 2025-05-11 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
